"""Add GES schools and school invitation system

Revision ID: e8fa7fe1de92
Revises: b5881bce9d82
Create Date: 2026-02-16 18:54:35.927011+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8fa7fe1de92"  # pragma: allowlist secret
down_revision: str | None = "b5881bce9d82"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ges_schools",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ges_id", sa.Integer(), nullable=False, comment="GES school ID"),
        sa.Column("name", sa.String(length=300), nullable=False, comment="Official school name"),
        sa.Column("region", sa.String(length=100), nullable=False, comment="Region name"),
        sa.Column("district", sa.String(length=100), nullable=False, comment="District name"),
        sa.Column(
            "school_type",
            sa.String(length=100),
            nullable=False,
            comment="School type (e.g., Senior High School)",
        ),
        sa.Column("courses_offered", sa.Text(), nullable=True, comment="Courses/programs offered"),
        sa.Column(
            "contact",
            sa.String(length=200),
            nullable=True,
            comment="Contact person from GES database",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
            comment="Creation timestamp (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
            comment="Last update timestamp (UTC)",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ges_id"),
    )
    op.create_table(
        "school_invitations",
        sa.Column("school_id", sa.Uuid(), nullable=False),
        sa.Column(
            "invitation_code", sa.String(length=20), nullable=False, comment="e.g., STMARYS-ABC123"
        ),
        sa.Column(
            "created_by",
            sa.String(length=100),
            nullable=True,
            comment="Headmaster/contact who created",
        ),
        sa.Column("expires_at", sa.String(), nullable=True, comment="Optional expiration date"),
        sa.Column(
            "max_teachers",
            sa.Integer(),
            nullable=True,
            comment="Max number of teachers who can use this code",
        ),
        sa.Column(
            "teachers_joined",
            sa.Integer(),
            nullable=False,
            comment="How many teachers have used this code",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Can still be used?"),
        sa.Column("id", sa.Uuid(), nullable=False, comment="UUID primary key"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
            comment="Creation timestamp (UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
            comment="Last update timestamp (UTC)",
        ),
        sa.ForeignKeyConstraint(["school_id"], ["schools.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invitation_code"),
    )
    op.add_column(
        "schools",
        sa.Column("ges_school_id", sa.Integer(), nullable=True, comment="FK to ges_schools table"),
    )
    op.add_column(
        "schools",
        sa.Column(
            "registered_by",
            sa.String(length=100),
            nullable=True,
            comment="Headmaster/contact who registered",
        ),
    )
    op.add_column(
        "schools",
        sa.Column(
            "registered_at",
            sa.String(),
            nullable=True,
            comment="When school registered in GapSense",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schools", "registered_at")
    op.drop_column("schools", "registered_by")
    op.drop_column("schools", "ges_school_id")
    op.drop_table("school_invitations")
    op.drop_table("ges_schools")
    # ### end Alembic commands ###
