"""Phase 4: Add Student.grade_canonical field

Revision ID: 5eef3213784c
Revises: d8e9f0a1b2c3
Create Date: 2026-03-18 14:57:50.494582+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5eef3213784c"
down_revision: str | None = "d8e9f0a1b2c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students",
        sa.Column(
            "grade_canonical",
            sa.String(length=16),
            nullable=True,
            comment="Phase 4: Canonical curriculum format (e.g., 'B7' from 'JHS1')",
        ),
    )
    op.create_index("idx_students_grade_canonical", "students", ["grade_canonical"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_students_grade_canonical", table_name="students")
    op.drop_column("students", "grade_canonical")
    # ### end Alembic commands ###
