"""Add pending status to diagnostic_sessions check constraint

Revision ID: 5857d9dac882
Revises: e8fa7fe1de92
Create Date: 2026-02-16 20:33:37.119728+00:00

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5857d9dac882"  # pragma: allowlist secret
down_revision: str | None = "e8fa7fe1de92"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
