"""Add teacher conversation state and class_name

Revision ID: eb4eab32e503
Revises: 88b3d73647b3
Create Date: 2026-02-16 12:04:39.141663+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eb4eab32e503"
down_revision: str | None = "88b3d73647b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teachers",
        sa.Column(
            "class_name",
            sa.String(length=100),
            nullable=True,
            comment="Class name (e.g., 'JHS 1A')",
        ),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "conversation_state",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Current flow state for teacher onboarding: {flow, step, data}",
        ),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "conversation_history",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Teacher conversation history for TEACHER-CONVERSATION-PARTNER",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teachers", "conversation_history")
    op.drop_column("teachers", "conversation_state")
    op.drop_column("teachers", "class_name")
    # ### end Alembic commands ###
