"""Add full_name field to Student model for parent selection UX

Revision ID: b5881bce9d82
Revises: 80fda3c19375
Create Date: 2026-02-16 13:03:00.202651+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5881bce9d82"  # pragma: allowlist secret
down_revision: str | None = "80fda3c19375"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students",
        sa.Column(
            "full_name",
            sa.String(length=200),
            nullable=True,
            comment="Full name from teacher's class register (e.g., 'Kwame Mensah')",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "full_name")
    # ### end Alembic commands ###
