"""Initial schema

Revision ID: f00f469d61b1
Revises:
Create Date: 2026-02-14 13:15:30.099777+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f00f469d61b1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # PHASE 1: Create all tables WITHOUT foreign key constraints
    op.create_table('curriculum_strands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strand_number', sa.SmallInteger(), nullable=False, comment='Strand number (1-5)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Strand name (e.g., 'Number', 'Algebra')"),
    sa.Column('color_hex', sa.String(length=7), nullable=True, comment='UI color code (#RRGGBB)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False, comment='Creation timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strand_number')
    )
    op.create_table('diagnostic_sessions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('initiated_by', sa.String(length=20), nullable=False, comment='Who started: parent, teacher, system, self'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='Where: whatsapp, web, app, sms, paper'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='in_progress, completed, abandoned, timed_out'),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False, comment='Session start time'),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('entry_grade', sa.String(length=5), nullable=False, comment='Grade level started at (B1-B9)'),
    sa.Column('entry_node_id', sa.UUID(), nullable=True, comment='First node tested'),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('nodes_tested', postgresql.ARRAY(sa.UUID()), nullable=False, comment='Array of tested node IDs'),
    sa.Column('nodes_mastered', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('nodes_gap', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('root_gap_node_id', sa.UUID(), nullable=True, comment='Deepest root gap identified'),
    sa.Column('root_gap_confidence', sa.Float(), nullable=True, comment='Confidence 0.0-1.0'),
    sa.Column('cascade_path_id', sa.Integer(), nullable=True, comment='Which cascade pattern matched'),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True, comment="e.g., 'claude-sonnet-4-5'"),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('ai_reasoning_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full chain-of-thought (encrypted at rest)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.CheckConstraint("channel IN ('whatsapp', 'web', 'app', 'sms', 'paper')", name='check_channel'),
    sa.CheckConstraint("initiated_by IN ('parent', 'teacher', 'system', 'self')", name='check_initiated_by'),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'abandoned', 'timed_out')", name='check_session_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_root_gap', 'diagnostic_sessions', ['root_gap_node_id'], unique=False)
    op.create_index('idx_sessions_status', 'diagnostic_sessions', ['status'], unique=False)
    op.create_index('idx_sessions_student', 'diagnostic_sessions', ['student_id'], unique=False)
    op.create_table('gap_profiles',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('mastered_nodes', postgresql.ARRAY(sa.UUID()), nullable=False, comment='Nodes confirmed mastered'),
    sa.Column('gap_nodes', postgresql.ARRAY(sa.UUID()), nullable=False, comment='Nodes with confirmed gaps'),
    sa.Column('uncertain_nodes', postgresql.ARRAY(sa.UUID()), nullable=False, comment='Need more data'),
    sa.Column('primary_gap_node', sa.UUID(), nullable=True, comment='The deepest root gap'),
    sa.Column('primary_cascade', sa.String(length=100), nullable=True, comment='Which cascade path'),
    sa.Column('secondary_gaps', postgresql.ARRAY(sa.UUID()), nullable=False, comment='Additional gap roots'),
    sa.Column('recommended_focus_node', sa.UUID(), nullable=True, comment='What to work on FIRST'),
    sa.Column('recommended_activity', sa.Text(), nullable=True, comment='Specific activity for parent'),
    sa.Column('estimated_grade_level', sa.String(length=5), nullable=True, comment='Functional grade level'),
    sa.Column('grade_gap', sa.SmallInteger(), nullable=True, comment='Difference from enrolled grade'),
    sa.Column('overall_confidence', sa.Float(), nullable=True, comment='How confident we are in this profile (0.0-1.0)'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='Only one current profile per student'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gap_profiles_current', 'gap_profiles', ['student_id'], unique=False, postgresql_where='is_current = TRUE')
    op.create_index('idx_gap_profiles_student', 'gap_profiles', ['student_id'], unique=False)
    op.create_table('prompt_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='diagnostic, parent_engagement, teacher, analysis'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Region name'),
    sa.Column('code', sa.String(length=5), nullable=False, comment='Region code'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('students',
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='First name only (some parents may not want to share last name)'),
    sa.Column('age', sa.SmallInteger(), nullable=True, comment='Approximate age'),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('current_grade', sa.String(length=5), nullable=False, comment='Enrolled grade (B1-B9)'),
    sa.Column('grade_as_of', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False, comment='When this grade was recorded'),
    sa.Column('teacher_id', sa.Uuid(), nullable=True),
    sa.Column('primary_parent_id', sa.Uuid(), nullable=False),
    sa.Column('secondary_parent_id', sa.Uuid(), nullable=True),
    sa.Column('home_language', sa.String(length=30), nullable=True, comment='L1 spoken at home'),
    sa.Column('school_language', sa.String(length=30), nullable=False, comment='Language of instruction at school'),
    sa.Column('latest_gap_profile_id', sa.Uuid(), nullable=True, comment='FK to current gap profile'),
    sa.Column('diagnosis_count', sa.Integer(), nullable=False),
    sa.Column('first_diagnosed_at', sa.DateTime(), nullable=True),
    sa.Column('last_diagnosed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.CheckConstraint("gender IN ('male', 'female', 'other')", name='check_gender'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_students_grade', 'students', ['current_grade'], unique=False)
    op.create_index('idx_students_parent', 'students', ['primary_parent_id'], unique=False)
    op.create_index('idx_students_school', 'students', ['school_id'], unique=False)
    op.create_table('curriculum_sub_strands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strand_id', sa.Integer(), nullable=False),
    sa.Column('sub_strand_number', sa.SmallInteger(), nullable=False, comment='Sub-strand number within strand'),
    sa.Column('phase', sa.String(length=10), nullable=False, comment="Phase: 'B1_B3', 'B4_B6', 'B7_B9'"),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strand_id', 'sub_strand_number', 'phase')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ges_district_code', sa.String(length=20), nullable=True, comment='Ghana Education Service district code'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'name')
    )
    op.create_table('prompt_versions',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False, comment="Semantic versioning: '1.0.0'"),
    sa.Column('name', sa.String(length=200), nullable=False, comment="e.g., 'Diagnostic Reasoning Prompt v2'"),
    sa.Column('system_prompt', sa.Text(), nullable=False, comment='The actual system prompt'),
    sa.Column('user_template', sa.Text(), nullable=True, comment='Template for user messages (with {{placeholders}})'),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Expected output format'),
    sa.Column('model_target', sa.String(length=50), nullable=False, comment='Which model this is optimized for'),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('test_cases_passed', sa.Integer(), nullable=False),
    sa.Column('test_cases_total', sa.Integer(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=True, comment='% accuracy on test cases'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='draft, testing, active, deprecated'),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(), nullable=True),
    sa.Column('deprecated_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.CheckConstraint("status IN ('draft', 'testing', 'active', 'deprecated')", name='check_prompt_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'version')
    )
    op.create_index('idx_prompt_versions_active', 'prompt_versions', ['category_id'], unique=False, postgresql_where="status = 'active'")
    op.create_table('curriculum_nodes',
    sa.Column('code', sa.String(length=20), nullable=False, comment="Node code (e.g., 'B2.1.1.1')"),
    sa.Column('grade', sa.String(length=5), nullable=False, comment="Grade level ('B1' through 'B9')"),
    sa.Column('strand_id', sa.Integer(), nullable=False),
    sa.Column('sub_strand_id', sa.Integer(), nullable=False),
    sa.Column('content_standard_number', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False, comment='Human-readable title'),
    sa.Column('description', sa.Text(), nullable=False, comment='Full description of mastery'),
    sa.Column('severity', sa.SmallInteger(), nullable=False, comment='Severity rating (1-5, 5=most critical)'),
    sa.Column('severity_rationale', sa.Text(), nullable=True, comment='Why this severity rating'),
    sa.Column('questions_required', sa.SmallInteger(), nullable=False, comment='Min questions to confirm mastery/gap'),
    sa.Column('confidence_threshold', sa.Float(), nullable=False, comment='Confidence threshold for diagnosis'),
    sa.Column('ghana_evidence', sa.Text(), nullable=True, comment='EGMA/NEA data, research citations'),
    sa.Column('population_status', sa.String(length=20), nullable=False, comment='Population status: skeleton/partial/full/validated'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.CheckConstraint("population_status IN ('skeleton', 'partial', 'full', 'validated')", name='check_population_status'),
    sa.CheckConstraint('severity >= 1 AND severity <= 5', name='check_severity_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_curriculum_nodes_code', 'curriculum_nodes', ['code'], unique=False)
    op.create_index('idx_curriculum_nodes_grade', 'curriculum_nodes', ['grade'], unique=False)
    op.create_index('idx_curriculum_nodes_severity', 'curriculum_nodes', ['severity'], unique=False, postgresql_ops={'severity': 'DESC'})
    op.create_table('parents',
    sa.Column('phone', sa.String(length=20), nullable=False, comment='WhatsApp number (primary identifier)'),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True, comment='How they want to be addressed'),
    sa.Column('preferred_language', sa.String(length=30), nullable=False, comment="ISO code or 'tw', 'ee', 'ga', 'dag'"),
    sa.Column('literacy_level', sa.String(length=20), nullable=True, comment='SENSITIVE: literate, semi_literate, non_literate. Determines message complexity. NEVER shared externally.'),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('community', sa.String(length=200), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=True, comment='Rolling engagement metric'),
    sa.Column('opted_in', sa.Boolean(), nullable=False, comment='Explicit WhatsApp opt-in'),
    sa.Column('opted_in_at', sa.DateTime(), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('prompt_test_cases',
    sa.Column('prompt_version_id', sa.UUID(), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('test_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Simulated input data'),
    sa.Column('expected_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='What the prompt should produce'),
    sa.Column('actual_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('school_type', sa.String(length=20), nullable=False, comment='Type: primary, jhs, combined, private'),
    sa.Column('ges_school_code', sa.String(length=30), nullable=True, comment='Ghana Education Service school code'),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('total_enrollment', sa.Integer(), nullable=True),
    sa.Column('language_of_instruction', sa.String(length=30), nullable=False, comment='Primary language of instruction'),
    sa.Column('dominant_l1', sa.String(length=30), nullable=True, comment='Most common mother tongue'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.CheckConstraint("school_type IN ('primary', 'jhs', 'combined', 'private')", name='check_school_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cascade_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Cascade name (e.g., 'Place Value Collapse')"),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=True, comment="e.g., 'Affects ~55% of students'"),
    sa.Column('diagnostic_entry_point', sa.UUID(), nullable=True, comment='Where to start testing for this cascade'),
    sa.Column('diagnostic_entry_question', sa.Text(), nullable=True),
    sa.Column('remediation_priority', sa.String(length=20), nullable=True, comment="Priority: 'HIGHEST', 'HIGH', 'MEDIUM-HIGH', 'MEDIUM'"),
    sa.Column('node_sequence', sa.ARRAY(sa.UUID()), nullable=False, comment='Ordered array of node IDs in the cascade'),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_indicators',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('indicator_code', sa.String(length=25), nullable=False, comment="Indicator code (e.g., 'B1.1.1.1.1')"),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('diagnostic_question_type', sa.String(length=30), nullable=True, comment="Question type: 'oral_counting', 'computation', 'word_problem'"),
    sa.Column('diagnostic_prompt_example', sa.Text(), nullable=True, comment='Example diagnostic question'),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_code')
    )
    op.create_table('curriculum_misconceptions',
    sa.Column('id', sa.String(length=30), nullable=False, comment="Misconception ID (e.g., 'MC-B2.1.3.1-01')"),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='What the misconception IS'),
    sa.Column('evidence', sa.Text(), nullable=False, comment='How it manifests (observable behavior)'),
    sa.Column('root_cause', sa.Text(), nullable=False, comment='WHY this misconception forms'),
    sa.Column('remediation_approach', sa.Text(), nullable=False, comment='How to fix it'),
    sa.Column('frequency_estimate', sa.String(length=50), nullable=True, comment="e.g., '55% of students'"),
    sa.Column('source_citation', sa.Text(), nullable=True, comment='Research source'),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum_prerequisites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False, comment='Source node (depends on target)'),
    sa.Column('target_node_id', sa.UUID(), nullable=False, comment='Target node (prerequisite)'),
    sa.Column('relationship_type', sa.String(length=20), nullable=False, comment="Type: 'requires', 'strengthens', 'enables'"),
    sa.Column('weight', sa.Float(), nullable=False, comment='Edge weight for path analysis'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("relationship_type IN ('requires', 'strengthens', 'enables')", name='check_relationship_type'),
    sa.CheckConstraint('source_node_id != target_node_id', name='check_no_self_loop'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_node_id', 'target_node_id')
    )
    op.create_index('idx_prerequisites_source', 'curriculum_prerequisites', ['source_node_id'], unique=False)
    op.create_index('idx_prerequisites_target', 'curriculum_prerequisites', ['target_node_id'], unique=False)
    op.create_table('parent_activities',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('gap_profile_id', sa.UUID(), nullable=True),
    sa.Column('focus_node_id', sa.UUID(), nullable=False),
    sa.Column('activity_title', sa.String(length=200), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=False, comment='The 3-minute activity'),
    sa.Column('materials_needed', sa.Text(), nullable=True, comment='What parent needs (bottle caps, paper, etc.)'),
    sa.Column('estimated_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Parent confirmed they started'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Parent confirmed completion'),
    sa.Column('parent_feedback', sa.Text(), nullable=True, comment='Optional feedback from parent'),
    sa.Column('follow_up_session_id', sa.UUID(), nullable=True),
    sa.Column('skill_improved', sa.Boolean(), nullable=True, comment='Did follow-up show improvement?'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activities_node', 'parent_activities', ['focus_node_id'], unique=False)
    op.create_index('idx_activities_parent', 'parent_activities', ['parent_id'], unique=False)
    op.create_table('parent_interactions',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False, comment='inbound or outbound'),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('wa_message_id', sa.String(length=100), nullable=True, comment='WhatsApp message ID for tracking'),
    sa.Column('message_type', sa.String(length=20), nullable=False, comment='text, image, voice, button, list, template'),
    sa.Column('interaction_purpose', sa.String(length=30), nullable=False, comment='diagnostic, activity, check_in, onboarding, feedback, reminder'),
    sa.Column('message_content', sa.Text(), nullable=True, comment='Actual message text (encrypted at rest)'),
    sa.Column('media_url', sa.Text(), nullable=True, comment='Media attachment URL'),
    sa.Column('template_name', sa.String(length=100), nullable=True, comment='WhatsApp template name if applicable'),
    sa.Column('language_used', sa.String(length=30), nullable=True, comment='Language this message was in'),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True, comment='Sentiment -1.0 to 1.0'),
    sa.Column('delivery_status', sa.String(length=20), nullable=False, comment='queued, sent, delivered, read, failed'),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.CheckConstraint("delivery_status IN ('queued', 'sent', 'delivered', 'read', 'failed')", name='check_delivery_status'),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name='check_direction'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interactions_parent', 'parent_interactions', ['parent_id'], unique=False)
    op.create_index('idx_interactions_purpose', 'parent_interactions', ['interaction_purpose'], unique=False)
    op.create_index('idx_interactions_student', 'parent_interactions', ['student_id'], unique=False)
    op.create_table('teachers',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='WhatsApp number'),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('grade_taught', sa.String(length=5), nullable=True, comment='Current grade (B1-B9)'),
    sa.Column('subjects', postgresql.ARRAY(sa.String(length=100)), nullable=True, comment='Array of subjects taught'),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('total_students_diagnosed', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp (NULL = not deleted)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostic_questions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_order', sa.SmallInteger(), nullable=False, comment='Order within session'),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('indicator_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False, comment='The actual question asked'),
    sa.Column('question_type', sa.String(length=30), nullable=False, comment='multiple_choice, free_response, image, voice'),
    sa.Column('question_media_url', sa.Text(), nullable=True, comment='Image/audio if applicable'),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('student_response', sa.Text(), nullable=True),
    sa.Column('response_media_url', sa.Text(), nullable=True, comment='Photo of exercise book, voice note'),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True, comment='How long student took'),
    sa.Column('error_pattern_detected', sa.String(length=100), nullable=True, comment='Which error pattern matched'),
    sa.Column('misconception_id', sa.String(length=30), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Detailed AI reasoning about the response'),
    sa.Column('asked_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='UUID primary key'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_node', 'diagnostic_questions', ['node_id'], unique=False)
    op.create_index('idx_questions_session', 'diagnostic_questions', ['session_id'], unique=False)
    op.create_table('indicator_error_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_id', sa.UUID(), nullable=False),
    sa.Column('error_description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False, comment="Severity: 'critical', 'standard', 'minor'"),
    sa.Column('indicates_gap_at', sa.UUID(), nullable=True, comment='Which node this error points to'),
    sa.Column('created_at', sa.String(), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("severity IN ('critical', 'standard', 'minor')", name='check_error_severity'),
    sa.PrimaryKeyConstraint('id')
    )

    # PHASE 2: Add all foreign key constraints
    # Base tables (no dependencies on other tables for FKs)
    op.create_foreign_key(None, 'curriculum_sub_strands', 'curriculum_strands', ['strand_id'], ['id'])
    op.create_foreign_key(None, 'districts', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(None, 'prompt_versions', 'prompt_categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'parents', 'districts', ['district_id'], ['id'])
    op.create_foreign_key(None, 'schools', 'districts', ['district_id'], ['id'])

    # Curriculum nodes
    op.create_foreign_key(None, 'curriculum_nodes', 'curriculum_strands', ['strand_id'], ['id'])
    op.create_foreign_key(None, 'curriculum_nodes', 'curriculum_sub_strands', ['sub_strand_id'], ['id'])

    # Tables that depend on curriculum_nodes
    op.create_foreign_key(None, 'cascade_paths', 'curriculum_nodes', ['diagnostic_entry_point'], ['id'])
    op.create_foreign_key(None, 'curriculum_indicators', 'curriculum_nodes', ['node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'curriculum_misconceptions', 'curriculum_nodes', ['node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'curriculum_prerequisites', 'curriculum_nodes', ['source_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'curriculum_prerequisites', 'curriculum_nodes', ['target_node_id'], ['id'], ondelete='CASCADE')

    # Prompt test cases
    op.create_foreign_key(None, 'prompt_test_cases', 'prompt_versions', ['prompt_version_id'], ['id'], ondelete='CASCADE')

    # Teachers
    op.create_foreign_key(None, 'teachers', 'schools', ['school_id'], ['id'])

    # Students (without circular FK to gap_profiles yet)
    op.create_foreign_key(None, 'students', 'parents', ['primary_parent_id'], ['id'])
    op.create_foreign_key(None, 'students', 'parents', ['secondary_parent_id'], ['id'])
    op.create_foreign_key(None, 'students', 'schools', ['school_id'], ['id'])
    op.create_foreign_key(None, 'students', 'teachers', ['teacher_id'], ['id'])

    # Diagnostic sessions (without circular FK yet)
    op.create_foreign_key(None, 'diagnostic_sessions', 'cascade_paths', ['cascade_path_id'], ['id'])
    op.create_foreign_key(None, 'diagnostic_sessions', 'curriculum_nodes', ['entry_node_id'], ['id'])
    op.create_foreign_key(None, 'diagnostic_sessions', 'curriculum_nodes', ['root_gap_node_id'], ['id'])
    op.create_foreign_key(None, 'diagnostic_sessions', 'prompt_versions', ['prompt_version_id'], ['id'])
    op.create_foreign_key(None, 'diagnostic_sessions', 'students', ['student_id'], ['id'])

    # Gap profiles (without circular FK yet)
    op.create_foreign_key(None, 'gap_profiles', 'curriculum_nodes', ['primary_gap_node'], ['id'])
    op.create_foreign_key(None, 'gap_profiles', 'curriculum_nodes', ['recommended_focus_node'], ['id'])
    op.create_foreign_key(None, 'gap_profiles', 'diagnostic_sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'gap_profiles', 'students', ['student_id'], ['id'])

    # Complete circular dependencies
    op.create_foreign_key(None, 'students', 'gap_profiles', ['latest_gap_profile_id'], ['id'])

    # Parent activities
    op.create_foreign_key(None, 'parent_activities', 'curriculum_nodes', ['focus_node_id'], ['id'])
    op.create_foreign_key(None, 'parent_activities', 'diagnostic_sessions', ['follow_up_session_id'], ['id'])
    op.create_foreign_key(None, 'parent_activities', 'gap_profiles', ['gap_profile_id'], ['id'])
    op.create_foreign_key(None, 'parent_activities', 'parents', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'parent_activities', 'students', ['student_id'], ['id'])

    # Parent interactions
    op.create_foreign_key(None, 'parent_interactions', 'parents', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'parent_interactions', 'prompt_versions', ['prompt_version_id'], ['id'])
    op.create_foreign_key(None, 'parent_interactions', 'students', ['student_id'], ['id'])

    # Diagnostic questions
    op.create_foreign_key(None, 'diagnostic_questions', 'curriculum_indicators', ['indicator_id'], ['id'])
    op.create_foreign_key(None, 'diagnostic_questions', 'curriculum_misconceptions', ['misconception_id'], ['id'])
    op.create_foreign_key(None, 'diagnostic_questions', 'curriculum_nodes', ['node_id'], ['id'])
    op.create_foreign_key(None, 'diagnostic_questions', 'diagnostic_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # Indicator error patterns
    op.create_foreign_key(None, 'indicator_error_patterns', 'curriculum_nodes', ['indicates_gap_at'], ['id'])
    op.create_foreign_key(None, 'indicator_error_patterns', 'curriculum_indicators', ['indicator_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # PHASE 1: Drop all foreign key constraints first
    # Indicator error patterns
    op.drop_constraint(None, 'indicator_error_patterns', type_='foreignkey')
    op.drop_constraint(None, 'indicator_error_patterns', type_='foreignkey')

    # Diagnostic questions
    op.drop_constraint(None, 'diagnostic_questions', type_='foreignkey')
    op.drop_constraint(None, 'diagnostic_questions', type_='foreignkey')
    op.drop_constraint(None, 'diagnostic_questions', type_='foreignkey')
    op.drop_constraint(None, 'diagnostic_questions', type_='foreignkey')

    # Parent interactions
    op.drop_constraint(None, 'parent_interactions', type_='foreignkey')
    op.drop_constraint(None, 'parent_interactions', type_='foreignkey')
    op.drop_constraint(None, 'parent_interactions', type_='foreignkey')

    # Parent activities
    op.drop_constraint(None, 'parent_activities', type_='foreignkey')
    op.drop_constraint(None, 'parent_activities', type_='foreignkey')
    op.drop_constraint(None, 'parent_activities', type_='foreignkey')
    op.drop_constraint(None, 'parent_activities', type_='foreignkey')
    op.drop_constraint(None, 'parent_activities', type_='foreignkey')

    # Circular dependency: students -> gap_profiles
    op.drop_constraint(None, 'students', type_='foreignkey')

    # Gap profiles
    op.drop_constraint(None, 'gap_profiles', type_='foreignkey')
    op.drop_constraint(None, 'gap_profiles', type_='foreignkey')
    op.drop_constraint(None, 'gap_profiles', type_='foreignkey')
    op.drop_constraint(None, 'gap_profiles', type_='foreignkey')

    # Diagnostic sessions
    op.drop_constraint(None, 'diagnostic_sessions', type_='foreignkey')
    op.drop_constraint(None, 'diagnostic_sessions', type_='foreignkey')
    op.drop_constraint(None, 'diagnostic_sessions', type_='foreignkey')
    op.drop_constraint(None, 'diagnostic_sessions', type_='foreignkey')
    op.drop_constraint(None, 'diagnostic_sessions', type_='foreignkey')

    # Students
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')

    # Teachers
    op.drop_constraint(None, 'teachers', type_='foreignkey')

    # Prompt test cases
    op.drop_constraint(None, 'prompt_test_cases', type_='foreignkey')

    # Curriculum prerequisites
    op.drop_constraint(None, 'curriculum_prerequisites', type_='foreignkey')
    op.drop_constraint(None, 'curriculum_prerequisites', type_='foreignkey')

    # Curriculum misconceptions
    op.drop_constraint(None, 'curriculum_misconceptions', type_='foreignkey')

    # Curriculum indicators
    op.drop_constraint(None, 'curriculum_indicators', type_='foreignkey')

    # Cascade paths
    op.drop_constraint(None, 'cascade_paths', type_='foreignkey')

    # Curriculum nodes
    op.drop_constraint(None, 'curriculum_nodes', type_='foreignkey')
    op.drop_constraint(None, 'curriculum_nodes', type_='foreignkey')

    # Parents
    op.drop_constraint(None, 'parents', type_='foreignkey')

    # Schools
    op.drop_constraint(None, 'schools', type_='foreignkey')

    # Prompt versions
    op.drop_constraint(None, 'prompt_versions', type_='foreignkey')

    # Districts
    op.drop_constraint(None, 'districts', type_='foreignkey')

    # Curriculum sub strands
    op.drop_constraint(None, 'curriculum_sub_strands', type_='foreignkey')

    # PHASE 2: Drop all tables
    op.drop_table('indicator_error_patterns')
    op.drop_index('idx_questions_session', table_name='diagnostic_questions')
    op.drop_index('idx_questions_node', table_name='diagnostic_questions')
    op.drop_table('diagnostic_questions')
    op.drop_table('teachers')
    op.drop_index('idx_interactions_student', table_name='parent_interactions')
    op.drop_index('idx_interactions_purpose', table_name='parent_interactions')
    op.drop_index('idx_interactions_parent', table_name='parent_interactions')
    op.drop_table('parent_interactions')
    op.drop_index('idx_activities_parent', table_name='parent_activities')
    op.drop_index('idx_activities_node', table_name='parent_activities')
    op.drop_table('parent_activities')
    op.drop_index('idx_prerequisites_target', table_name='curriculum_prerequisites')
    op.drop_index('idx_prerequisites_source', table_name='curriculum_prerequisites')
    op.drop_table('curriculum_prerequisites')
    op.drop_table('curriculum_misconceptions')
    op.drop_table('curriculum_indicators')
    op.drop_table('cascade_paths')
    op.drop_table('schools')
    op.drop_table('prompt_test_cases')
    op.drop_table('parents')
    op.drop_index('idx_curriculum_nodes_severity', table_name='curriculum_nodes', postgresql_ops={'severity': 'DESC'})
    op.drop_index('idx_curriculum_nodes_grade', table_name='curriculum_nodes')
    op.drop_index('idx_curriculum_nodes_code', table_name='curriculum_nodes')
    op.drop_table('curriculum_nodes')
    op.drop_index('idx_prompt_versions_active', table_name='prompt_versions', postgresql_where="status = 'active'")
    op.drop_table('prompt_versions')
    op.drop_table('districts')
    op.drop_table('curriculum_sub_strands')
    op.drop_index('idx_students_school', table_name='students')
    op.drop_index('idx_students_parent', table_name='students')
    op.drop_index('idx_students_grade', table_name='students')
    op.drop_table('students')
    op.drop_table('regions')
    op.drop_table('prompt_categories')
    op.drop_index('idx_gap_profiles_student', table_name='gap_profiles')
    op.drop_index('idx_gap_profiles_current', table_name='gap_profiles', postgresql_where='is_current = TRUE')
    op.drop_table('gap_profiles')
    op.drop_index('idx_sessions_student', table_name='diagnostic_sessions')
    op.drop_index('idx_sessions_status', table_name='diagnostic_sessions')
    op.drop_index('idx_sessions_root_gap', table_name='diagnostic_sessions')
    op.drop_table('diagnostic_sessions')
    op.drop_table('curriculum_strands')
    # ### end Alembic commands ###
