"""Make primary_parent_id nullable for teacher-created students

Revision ID: 9308455ddbbd
Revises: eb4eab32e503
Create Date: 2026-02-16 12:14:15.314062+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9308455ddbbd"
down_revision: str | None = "eb4eab32e503"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students",
        "primary_parent_id",
        existing_type=sa.UUID(),
        nullable=True,
        comment="Linked when parent onboards",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students",
        "primary_parent_id",
        existing_type=sa.UUID(),
        nullable=False,
        comment=None,
        existing_comment="Linked when parent onboards",
    )
    # ### end Alembic commands ###
