"""Make last_message_at and session_expires_at timezone-aware

Revision ID: c1de30aa4d19
Revises: 353744cdbdc4
Create Date: 2026-02-15 22:26:02.257425+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c1de30aa4d19"  # pragma: allowlist secret
down_revision: str | None = "353744cdbdc4"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parents",
        "last_message_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Last WhatsApp message received from parent",
        existing_nullable=True,
    )
    op.alter_column(
        "parents",
        "session_expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="24-hour session window expiry (WhatsApp constraint)",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parents",
        "session_expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="24-hour session window expiry (WhatsApp constraint)",
        existing_nullable=True,
    )
    op.alter_column(
        "parents",
        "last_message_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="Last WhatsApp message received from parent",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
