"""Add diagnostic_consent fields and fix onboarded_at timezone

Revision ID: 88b3d73647b3
Revises: ae0be4bd4a74
Create Date: 2026-02-15 23:35:21.917276+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88b3d73647b3"
down_revision: str | None = "ae0be4bd4a74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parents",
        sa.Column(
            "diagnostic_consent",
            sa.Boolean(),
            nullable=True,
            comment="Parent consent for diagnostic assessments (True=yes, False=no, None=not asked)",
        ),
    )
    op.add_column(
        "parents",
        sa.Column(
            "diagnostic_consent_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When diagnostic consent was recorded",
        ),
    )
    op.alter_column(
        "parents",
        "onboarded_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        comment="When parent completed onboarding flow",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parents",
        "onboarded_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="When parent completed onboarding flow",
        existing_nullable=True,
    )
    op.drop_column("parents", "diagnostic_consent_at")
    op.drop_column("parents", "diagnostic_consent")
    # ### end Alembic commands ###
