"""Fix curriculum_strands created_at type and add named FK constraints

Revision ID: 2adcce6e7173
Revises: f00f469d61b1
Create Date: 2026-02-14 22:42:45.838660+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2adcce6e7173"
down_revision: str | None = "f00f469d61b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "curriculum_nodes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "curriculum_nodes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_curriculum_nodes_severity"), table_name="curriculum_nodes")
    op.create_index(
        "idx_curriculum_nodes_severity",
        "curriculum_nodes",
        ["severity"],
        unique=False,
        postgresql_ops={"severity": "DESC"},
    )
    op.alter_column(
        "curriculum_strands",
        "created_at",
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(),
        existing_comment="Creation timestamp",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "districts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "districts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "parents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "parents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "prompt_versions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "prompt_versions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "schools",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "schools",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "students",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "students",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "teachers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "teachers",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("NOW()"),
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teachers",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "teachers",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "students",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "students",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "schools",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "schools",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "prompt_versions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "prompt_versions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "parents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "parents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "districts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "districts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "curriculum_strands",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(),
        existing_comment="Creation timestamp",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        "idx_curriculum_nodes_severity",
        table_name="curriculum_nodes",
        postgresql_ops={"severity": "DESC"},
    )
    op.create_index(
        op.f("idx_curriculum_nodes_severity"),
        "curriculum_nodes",
        [sa.literal_column("severity DESC")],
        unique=False,
    )
    op.alter_column(
        "curriculum_nodes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Last update timestamp (UTC)",
        existing_nullable=False,
    )
    op.alter_column(
        "curriculum_nodes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_comment="Creation timestamp (UTC)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
