"""Add conversation state fields to Parent model

Revision ID: 353744cdbdc4
Revises: 2adcce6e7173
Create Date: 2026-02-15 22:02:34.924849+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "353744cdbdc4"  # pragma: allowlist secret
down_revision: str | None = "2adcce6e7173"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parents",
        sa.Column(
            "conversation_state",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Current flow state: {flow, step, data}. Enables multi-step conversations.",
        ),
    )
    op.add_column(
        "parents",
        sa.Column(
            "last_message_at",
            sa.DateTime(),
            nullable=True,
            comment="Last WhatsApp message received from parent",
        ),
    )
    op.add_column(
        "parents",
        sa.Column(
            "session_expires_at",
            sa.DateTime(),
            nullable=True,
            comment="24-hour session window expiry (WhatsApp constraint)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parents", "session_expires_at")
    op.drop_column("parents", "last_message_at")
    op.drop_column("parents", "conversation_state")
    # ### end Alembic commands ###
